dbt_dims_facts:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: password
      port: 5432
      dbname: olist_db
      schema: public
      threads: 1