postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: password
      port: 5432
      dbname: olist_db
      schema: public
      threads: 1

snowflake:
  target: dev
  outputs:  
    dev:
      type: snowflake
      account: 
      user: 
      password: 
      role: ACCOUNTADMIN               
      database: ecommerce_db_demo
      schema: ECOMMERCE_DEMO
      warehouse: COMPUTE_WH